[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pandss"
version = "0.6.12"
dependencies = [
    "pyhecdss",
    "pandas",
    "pint",
    "packaging"
]

[tool.setuptools]
include-package-data = true