[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pandss"
version = "0.3"
dependencies = [
    "pyhecdss",
    "pandas",
]

[tool.setuptools]
packages = ["pandss"]