[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pandss"
version = "0.5.4"
dependencies = [
    "pyhecdss",
    "pandas",
]

[tool.setuptools]
packages = ["pandss", "pandss.engines", "pandss.units"]
include-package-data = true
