{% set data = load_file_data('../pyproject.toml', from_recipe_dir=True) %}


package:
  name: pandss
  version: {{ data['project']['version'] }}

source:
  path: ..

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - pip
    - python=3.11
    - setuptools

  run:
    - python=3.11
    - pyhecdss
    - pandas
    - packaging

about:
  home: https://github.com/CentralValleyModeling/pandss