package:
  name: pandss
  version: 0.4.1

source:
  path: ../pandss

requirements:
  build:
    - pip
    - python=3.11
    - setuptools

  run:
    - python=3.11
    - pyhecdss
    - pandas

about:
  home: https://github.com/CentralValleyModeling/pandss